### ISSUE TITLE
panic: runtime error: index out of range [1] with length 0

### ISSUE THREAD

**Issue by ionutnechita** [gocolly/colly#437]
Code:
Instagram example
 https://github.com/gocolly/colly/blob/master/_examples/instagram/instagram.go

Run:
 go run instagram.go kimkardashian

Error:
 panic: runtime error: index out of range [1] with length 0

goroutine 1 [running]:
main.main.func2.1(0xc0000e6000)
        C:/Users/ionutsss/go/src/instagramExtract/instagram.go:110 +0x130
github.com/gocolly/colly/v2.(*Collector).handleOnResponse(0xc000478000, 0xc0000e6000)
        C:/Users/ionutsss/go/src/github.com/gocolly/colly/v2/colly.go:964 +0x70
github.com/gocolly/colly/v2.(*Collector).fetch(0xc000478000, 0xc000258370, 0x48, 0x95bfad, 0x3, 0x1, 0x0, 0x0, 0xc0002089f0, 0xc00021fce0, ...)
        C:/Users/ionutsss/go/src/github.com/gocolly/colly/v2/colly.go:630 +0x3fd
github.com/gocolly/colly/v2.(*Collector).scrape(0xc000478000, 0xc000258370, 0x48, 0x95bfad, 0x3, 0x1, 0x0, 0x0, 0x0, 0xc00021fce0, ...)
        C:/Users/ionutsss/go/src/github.com/gocolly/colly/v2/colly.go:544 +0x46a
github.com/gocolly/colly/v2.(*Collector).Visit(0xc000478000, 0xc0002582d0, 0x48, 0xc0002582d0, 0x48)
        C:/Users/ionutsss/go/src/github.com/gocolly/colly/v2/colly.go:416 +0x89
main.main.func2(0xc00026afc0)
        C:/Users/ionutsss/go/src/instagramExtract/instagram.go:113 +0x11a
github.com/gocolly/colly/v2.(*Collector).handleOnHTML.func1(0x0, 0xc00021fc20)
        C:/Users/ionutsss/go/src/github.com/gocolly/colly/v2/colly.go:991 +0x93
github.com/PuerkitoBio/goquery.(*Selection).Each(0xc00021fbf0, 0xc0002c3c88, 0x4)
        C:/Users/ionutsss/go/src/github.com/PuerkitoBio/goquery/iteration.go:10 +0x5a
github.com/gocolly/colly/v2.(*Collector).handleOnHTML(0xc000091860, 0xc000230100, 0x0, 0x0)
        C:/Users/ionutsss/go/src/github.com/gocolly/colly/v2/colly.go:981 +0x222
github.com/gocolly/colly/v2.(*Collector).fetch(0xc000091860, 0xc0000b84c0, 0x22, 0x95bfad, 0x3, 0x1, 0x0, 0x0, 0xc000168060, 0xc00015ccc0, ...)
        C:/Users/ionutsss/go/src/github.com/gocolly/colly/v2/colly.go:632 +0x418
github.com/gocolly/colly/v2.(*Collector).scrape(0xc000091860, 0xc0000b84c0, 0x22, 0x95bfad, 0x3, 0x1, 0x0, 0x0, 0x0, 0xc00015ccc0, ...)
        C:/Users/ionutsss/go/src/github.com/gocolly/colly/v2/colly.go:544 +0x46a
github.com/gocolly/colly/v2.(*Collector).Visit(0xc000091860, 0xc0000ca3c0, 0x22, 0xc0000a2090, 0xd)
        C:/Users/ionutsss/go/src/github.com/gocolly/colly/v2/colly.go:416 +0x89
main.main()
        C:/Users/ionutsss/go/src/instagramExtract/instagram.go:188 +0x2f4
exit status 2

>>> go version go1.14beta1 windows/amd64
date
The current date is: Sat 01/18/2020

**Comment by Pedro-Pessoa** [comment]
Any updates on this?

**Comment by ionutnechita** [comment]
Hi @Pedro Pessoa,

I retested this issue with:  go1.16.3 linux/amd64. And is reproduced.

./main  kimkardashian 
panic: runtime error: index out of range [1] with length 0

goroutine 1 [running]:
main.main.func2.1(0xc0003a4000)
        /localdisk/ionutnechita/test2/main.go:110 +0x125
github.com/gocolly/colly/v2.(*Collector).handleOnResponse(0xc0003f6000, 0xc0003a4000)
        /home/ionutnechita/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1035 +0x69
github.com/gocolly/colly/v2.(*Collector).fetch(0xc0003f6000, 0xc000358370, 0x48, 0x98cf19, 0x3, 0x1, 0x0, 0x0, 0xc00059c060, 0xc00061c060, ...)
        /home/ionutnechita/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:674 +0x485
github.com/gocolly/colly/v2.(*Collector).scrape(0xc0003f6000, 0xc000358370, 0x48, 0x98cf19, 0x3, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
        /home/ionutnechita/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:577 +0x48c
github.com/gocolly/colly/v2.(*Collector).Visit(0xc0003f6000, 0xc0003582d0, 0x48, 0xc0003582d0, 0x48)
        /home/ionutnechita/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:446 +0x85
main.main.func2(0xc0000e0060)
        /localdisk/ionutnechita/test2/main.go:113 +0x113
github.com/gocolly/colly/v2.(*Collector).handleOnHTML.func1(0x0, 0xc00061dd10)
        /home/ionutnechita/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1074 +0x8c
github.com/PuerkitoBio/goquery.(*Selection).Each(0xc00061dce0, 0xc000271c50, 0x4)
        /home/ionutnechita/go/pkg/mod/github.com/!puerkito!bio/goquery@v1.5.1/iteration.go:10 +0x53
github.com/gocolly/colly/v2.(*Collector).handleOnHTML(0xc00024b340, 0xc0001d8200, 0x0, 0x0)
        /home/ionutnechita/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1064 +0x2aa
github.com/gocolly/colly/v2.(*Collector).fetch(0xc00024b340, 0xc0001b4150, 0x23, 0x98cf19, 0x3, 0x1, 0x0, 0x0, 0xc0002fbe80, 0xc0002c1350, ...)
        /home/ionutnechita/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:676 +0x4a5
github.com/gocolly/colly/v2.(*Collector).scrape(0xc00024b340, 0xc0001b4150, 0x23, 0x98cf19, 0x3, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
        /home/ionutnechita/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:577 +0x48c
github.com/gocolly/colly/v2.(*Collector).Visit(0xc00024b340, 0xc0001b40f0, 0x23, 0x7fff3ccb56ce, 0xd)
        /home/ionutnechita/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:446 +0x85
main.main()
        /localdisk/ionutnechita/test2/main.go:188 +0x2f5

**Comment by Pedro-Pessoa** [comment]
I'm also able to reproduce the same issue. Any instagram account returns the same error.

**Comment by Pedro-Pessoa** [comment]
@asciimoo Sorry for the ping, Adam. But, can I bring your attention to this please?
Issue hasn't got a response in a while. Thanks!
