### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference on local_files example

### ISSUE THREAD

**Issue by dpsarrou** [gocolly/colly#463]
Hey guys,

I've run to a segmentation fault while trying to run the `local_files` example. Reproducing it is very easy:

```
git clone https://github.com/gocolly/colly
cd _examples/local_files
go build -o example local_files.go && ./example
```

Output:

```
file:///Users/cminor/projects/gocolly/colly/_examples/local_files/html/index.html
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1495d5b]

goroutine 1 [running]:
github.com/gocolly/colly/v2.(*httpBackend).Do(0xc0001b4bd0, 0xc0001a8200, 0xa00000, 0xc0001afcf0, 0x0, 0x0, 0x0)
        /Users/cminor/projects/gocolly/colly/http_backend.go:202 +0x66b
github.com/gocolly/colly/v2.(*httpBackend).Cache(0xc0001b4bd0, 0xc0001a8200, 0xa00000, 0xc0001afcf0, 0x0, 0x0, 0xc00007e187, 0x4e, 0x8)
        /Users/cminor/projects/gocolly/colly/http_backend.go:134 +0x77
github.com/gocolly/colly/v2.(*Collector).fetch(0xc0001bc380, 0xc00007e2a0, 0x55, 0x15abb58, 0x3, 0x1, 0x0, 0x0, 0xc0001be1b0, 0xc0001b4cc0, ...)
        /Users/cminor/projects/gocolly/colly/colly.go:650 +0x2a8
github.com/gocolly/colly/v2.(*Collector).scrape(0xc0001bc380, 0xc00007e2a0, 0x55, 0x15abb58, 0x3, 0x1, 0x0, 0x0, 0x0, 0xc0001b4cc0, ...)
        /Users/cminor/projects/gocolly/colly/colly.go:574 +0x463
github.com/gocolly/colly/v2.(*Collector).Visit(0xc0001bc380, 0xc00007e180, 0x55, 0xc000028200, 0x3e)
        /Users/cminor/projects/gocolly/colly/colly.go:446 +0x82
main.main()
        /Users/cminor/projects/gocolly/colly/_examples/local_files/local_files.go:35 +0x3c1
```

I've debugged the issue and traced it back to [line 202 on http_backend.go](https://github.com/gocolly/colly/blob/722d45495c3f30dfb112265deca8a73186ef15ac/http_backend.go#L202) and specifically this [commit](https://github.com/gocolly/colly/commit/b8d15965a192d74d6c7a7dddb0173402a8adc968). The code uses `res.Request` to read the `URL.Path`, while the `res.Request` is actually `nil` in this specific case. Since `request` is already available in this method a fix can be to read the value directly from it, instead of `res.Request`. I will be preparing a pull request shortly to address this.

**Comment by asciimoo** [comment]
fixed in #464
