### ISSUE TITLE
Fails to scrape site with google font css - `unsupported protocol scheme`

### ISSUE THREAD

**Issue by mattburns** [gocolly/colly#559]
Error message below trying to scrape the site https://www.printelligently.com hosted on squarespace.com

```
> goclone https://www.printelligently.com
Extracting -->  https://www.printelligently.com
Css found --> //fonts.googleapis.com/css?family=Poppins:700,500,300,400
Extracting -->  //fonts.googleapis.com/css?family=Poppins:700,500,300,400
panic: Get "//fonts.googleapis.com/css?family=Poppins:700,500,300,400": unsupported protocol scheme ""

goroutine 18 [running]:
github.com/imthaghost/goclone/crawler.Extractor(0xc0000a72c0, 0x39, 0xc0001e0320, 0x42)
	/Users/ghost/go/src/github.com/imthaghost/goclone/crawler/extractor.go:35 +0x2cc
github.com/imthaghost/goclone/crawler.Collector.func1(0xc0000be5a0)
	/Users/ghost/go/src/github.com/imthaghost/goclone/crawler/collector.go:25 +0x169
github.com/gocolly/colly.(*Collector).handleOnHTML.func1(0x0, 0xc0004ae030)
	/Users/ghost/go/pkg/mod/github.com/gocolly/colly@v1.2.0/colly.go:963 +0x8c
github.com/PuerkitoBio/goquery.(*Selection).Each(0xc0004ae000, 0xc000063e68, 0x16)
	/Users/ghost/go/pkg/mod/github.com/!puerkito!bio/goquery@v1.5.1/iteration.go:10 +0x53
github.com/gocolly/colly.(*Collector).handleOnHTML(0xc00011dba0, 0xc000078000, 0x0, 0x0)
	/Users/ghost/go/pkg/mod/github.com/gocolly/colly@v1.2.0/colly.go:953 +0x21b
github.com/gocolly/colly.(*Collector).fetch(0xc00011dba0, 0xc0002ae180, 0x1f, 0x1687532, 0x3, 0x1, 0x0, 0x0, 0xc0001dba60, 0xc0001d3ec0, ...)
	/Users/ghost/go/pkg/mod/github.com/gocolly/colly@v1.2.0/colly.go:623 +0x411
created by github.com/gocolly/colly.(*Collector).scrape
	/Users/ghost/go/pkg/mod/github.com/gocolly/colly@v1.2.0/colly.go:532 +0x3b1
```

**Comment by WGH-** [comment]
I think this should've been fixed by #479 (the site has `<base href="">`)
