### ISSUE TITLE
calling functions on colly.Collector throws a runtime error

### ISSUE THREAD

**Issue by kvogli** [gocolly/colly#695]
Hi. I'm new to golang and colly and i ran into this error today. I am running `go version go1.17.8 linux/amd64`
````
# command-line-arguments
panic: runtime error: index out of range [4195959] with length 3806

goroutine 1 [running]:
cmd/link/internal/loader.(*Loader).resolve(0x17004fc59f, 0xc000883b00, {0xb45760, 0xc0})
        /usr/lib/go/src/cmd/link/internal/loader/loader.go:655 +0x1bd
cmd/link/internal/loader.Aux.Sym({0x7f49cc9aa84b, 0xc000883b00, 0xc000806000})
        /usr/lib/go/src/cmd/link/internal/loader/loader.go:71 +0x35
cmd/link/internal/ld.(*deadcodePass).flood(0xc0000c8c38)
        /usr/lib/go/src/cmd/link/internal/ld/deadcode.go:225 +0xbd1
cmd/link/internal/ld.deadcode(0xc000192000)
        /usr/lib/go/src/cmd/link/internal/ld/deadcode.go:365 +0x14f
cmd/link/internal/ld.Main(_, {0x20, 0x20, 0x1, 0x7, 0x10, 0x0, {0x0, 0x0}, {0x679bea, ...}, ...})
        /usr/lib/go/src/cmd/link/internal/ld/main.go:252 +0xdb2
main.main()
        /usr/lib/go/src/cmd/link/main.go:69 +0x1005
````

To reproduce the error, you can create an empty project (directory) with a `main.go` file, run `go mod init example.com/test` and `go get github.com/gocolly/colly`. Copy paste this code sample in your `main.go` file and execute with `go run main.go`:

```
package main

import (
	"fmt"
	"github.com/gocolly/colly"
)

func main() {
	c := colly.NewCollector()

	// Find and visit all links
	c.OnHTML("a[href]", func(e *colly.HTMLElement) {
		e.Request.Visit(e.Attr("href"))
	})

	c.OnRequest(func(r *colly.Request) {
		fmt.Println("Visiting", r.URL)
	})

	c.Visit("http://go-colly.org/")
}
```
This was working fine few days ago. I've tried installing different versions but had no luck.

**Comment by kvogli** [comment]
reinstalling latest version works
