### ISSUE TITLE
[bug]fmt.(*pp).doPrintf(0xc02967ec30, {0x153ffc5, 0x35}, {0xc00e695d50?, 0x3, 0x3})

### ISSUE THREAD

**Issue by hktalent** [gocolly/colly#700]
code :
https://github.com/hktalent/ScrapySite
```go
r.Scrapy.Limit(&colly.LimitRule{DomainGlob: "*", Parallelism: 256})
extensions.RandomUserAgent(r.Scrapy)
extensions.Referer(r.Scrapy)
```
error:
```
fmt.(*buffer).writeString(...)
        /usr/local/Cellar/go/1.18/libexec/src/fmt/print.go:82
fmt.(*pp).doPrintf(0xc02967ec30, {0x153ffc5, 0x35}, {0xc00e695d50?, 0x3, 0x3})
        /usr/local/Cellar/go/1.18/libexec/src/fmt/print.go:987 +0x137
fmt.Sprintf({0x153ffc5, 0x35}, {0xc00e695d50, 0x3, 0x3})
        /usr/local/Cellar/go/1.18/libexec/src/fmt/print.go:219 +0x59
github.com/gocolly/colly/v2/extensions.genFirefoxUA()
        /Users/51pwn/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/extensions/random_user_agent.go:181 +0x114
github.com/gocolly/colly/v2/extensions.RandomUserAgent.func1(0xc00e553300)
        /Users/51pwn/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/extensions/random_user_agent.go:24 +0x53
github.com/gocolly/colly/v2.(*Collector).handleOnRequest(0x0?, 0xc00e553300)
        /Users/51pwn/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1023 +0x15d
github.com/gocolly/colly/v2.(*Collector).fetch(0xc0001ad340, {0x0?, 0x0?}, {0x15230d5, 0x3}, 0x6, {0x0?, 0x0}, 0x0?, 0xc006f99560, ...)
        /Users/51pwn/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:628 +0x273
created by github.com/gocolly/colly/v2.(*Collector).scrape
        /Users/51pwn/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:574 +0x585
```

**Comment by hktalent** [comment]
```
goroutine 14671 [semacquire]:
github.com/gocolly/colly/v2/extensions.genOperaUA()
        /Users/51pwn/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/extensions/random_user_agent.go:197 +0xa7
github.com/gocolly/colly/v2/extensions.RandomUserAgent.func1(0xc01a7ed400)
        /Users/51pwn/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/extensions/random_user_agent.go:24 +0x53
github.com/gocolly/colly/v2.(*Collector).handleOnRequest(0xc002e24858?, 0xc01a7ed400)
        /Users/51pwn/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1023 +0x15d
github.com/gocolly/colly/v2.(*Collector).fetch(0xc0001d3340, {0xc0029f69a0?, 0x16b0300000003?}, {0x1523355, 0x3}, 0x16, {0x0?, 0x0}, 0x1?, 0xc0016b00c0, ...)
        /Users/51pwn/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:628 +0x273
created by github.com/gocolly/colly/v2.(*Collector).scrape
        /Users/51pwn/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:574 +0x585

goroutine 14691 [semacquire]:
github.com/gocolly/colly/v2/extensions.genOperaUA()
        /Users/51pwn/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/extensions/random_user_agent.go:197 +0xa7
github.com/gocolly/colly/v2/extensions.RandomUserAgent.func1(0xc01aa90980)
        /Users/51pwn/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/extensions/random_user_agent.go:24 +0x53
github.com/gocolly/colly/v2.(*Collector).handleOnRequest(0x90909090909090a?, 0xc01aa90980)
        /Users/51pwn/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1023 +0x15d
github.com/gocolly/colly/v2.(*Collector).fetch(0xc0001d3340, {0xa30316b6e616c62?, 0x9090909?}, {0x1523355, 0x3}, 0x12, {0x0?, 0x0}, 0x38320033?, 0xc001194060, ...)
        /Users/51pwn/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:628 +0x273
created by github.com/gocolly/colly/v2.(*Collector).scrape
        /Users/51pwn/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:574 +0x585

goroutine 14641 [runnable]:
github.com/gocolly/colly/v2/extensions.genFirefoxUA()
        /Users/51pwn/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/extensions/random_user_agent.go:181 +0xa5
github.com/gocolly/colly/v2/extensions.RandomUserAgent.func1(0xc01a6fde80)
        /Users/51pwn/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/extensions/random_user_agent.go:24 +0x53
github.com/gocolly/colly/v2.(*Collector).handleOnRequest(0x0?, 0xc01a6fde80)
        /Users/51pwn/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1023 +0x15d
github.com/gocolly/colly/v2.(*Collector).fetch(0xc0001d3340, {0x0?, 0x0?}, {0x1523355, 0x3}, 0x9, {0x0?, 0x0}, 0x0?, 0xc001465980, ...)
        /Users/51pwn/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:628 +0x273
created by github.com/gocolly/colly/v2.(*Collector).scrape
        /Users/51pwn/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:574 +0x585
```

**Comment by hktalent** [comment]
```
goroutine 32418 [runnable]:
net/textproto.MIMEHeader.Set(...)
        /usr/local/Cellar/go/1.18/libexec/src/net/textproto/header.go:22
net/http.Header.Set(...)
        /usr/local/Cellar/go/1.18/libexec/src/net/http/header.go:40
github.com/gocolly/colly/v2/extensions.Referer.func2(0xc00fb81080)
        /Users/51pwn/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/extensions/referer.go:16 +0x85
github.com/gocolly/colly/v2.(*Collector).handleOnRequest(0x0?, 0xc00fb81080)
        /Users/51pwn/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:1023 +0x15d
github.com/gocolly/colly/v2.(*Collector).fetch(0xc00016b340, {0x0?, 0x0?}, {0x1523015, 0x3}, 0xa, {0x0?, 0x0}, 0x0?, 0xc00a72aa50, ...)
        /Users/51pwn/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:628 +0x273
created by github.com/gocolly/colly/v2.(*Collector).scrape
        /Users/51pwn/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:574 +0x585

goroutine 32434 [runnable]:
net/textproto.MIMEHeader.Set(...)
        /usr/local/Cellar/go/1.18/libexec/src/net/textproto/header.go:22
net/http.Header.Set(...)
        /usr/local/Cellar/go/1.18/libexec/src/net/http/header.go:40
github.com/gocolly/colly/v2/extensions.Referer.func2(0xc00f4dc100)
        /Users/51pwn/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/extensions/referer.go:16 +0x85
github.com/gocolly/colly/v2.(*Collector).handleOnRequest(0x676965682d656e69?, 0xc0^Cgithub.com/gocolly/colly/v2.(*Collector).fetch(0xc00016b340, {0x72203a6e67696c61?, 0x90a0d3b74686769?}, {0x1523015, 0x3}, 0x15, {0x0?, 0x0}, 0x68223d7373616c63?, 0xc00a804540, ...)
        /Users/51pwn/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:628 +0x273
created by github.com/gocolly/colly/v2.(*Collector).scrape
        /Users/51pwn/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/colly.go:574 +0x585

goroutine 32404 [runnable]:
net/textproto.MIMEHeader.Set(...)
        /usr/local/Cellar/go/1.18/libexec/src/net/textproto/header.go:22
net/http.Header.Set(...)
        /usr/local/Cellar/go/1.18/libexec/src/net/http/header.go:40
github.com/gocolly/colly/v2/extensions.Referer.func2(0xc00f3f8a00)
        /Users/51pwn/go/pkg/mod/github.com/gocolly/colly/v2@v2.1.0/extensions/referer.go:16 +0x85
github.com/gocolly/colly/v2.(*Collector).handleOnRequest(0x41726573752e726f?,
```
