### ISSUE TITLE
Colly instagram crawler sent panic 

### ISSUE THREAD

**Issue by hosseinkhojany** [gocolly/colly#717]
My first three or four tests were ok and there were no problems until the next test had problems

the entry_data field which is the most important field in Instagram response, has this in it:
 "entry_data": {
        "LoginAndSignupPage": [
            {
                "captcha": {
                    "enabled": false,
                    "key": ""
                },
                "gdpr_required": false,
                "tos_version": "row",
                "username_hint": ""
            }
        ]
    },

But the previous requests were like this

"entry_data": {
        "ProfilePage": [
            {
                  -------
                  -------
                  -------
                  -------
                  -------
            }
}

panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.main.func2(0xc0001d8d20)
        /home/khoujani/Desktop/eSport98/backend/eSport98-back/app/main2.go:129 +0x5e5
github.com/gocolly/colly.(*Collector).handleOnHTML.func1(0xc0000ae020?, 0xc0005519b0)
        /home/khoujani/go/pkg/mod/github.com/gocolly/colly@v1.2.0/colly.go:963 +0x78
github.com/PuerkitoBio/goquery.(*Selection).Each(0xc000551980, 0xc000143c48)
        /home/khoujani/go/pkg/mod/github.com/!puerkito!bio/goquery@v1.8.0/iteration.go:10 +0x46
github.com/gocolly/colly.(*Collector).handleOnHTML(0xc0002729c0, 0xc0002840c0)
        /home/khoujani/go/pkg/mod/github.com/gocolly/colly@v1.2.0/colly.go:953 +0x24f
github.com/gocolly/colly.(*Collector).fetch(0xc0002729c0, {0xa?, 0x3?}, {0x92eaac, 0x3}, 0x1, {0x0?, 0x0}, 0xc0000cfe20?, 0xc0002514d0, ...)
        /home/khoujani/go/pkg/mod/github.com/gocolly/colly@v1.2.0/colly.go:623 +0x68d
github.com/gocolly/colly.(*Collector).scrape(0xc0002729c0, {0xc0000c4b00, 0x20}, {0x92eaac, 0x3}, 0x1, {0x0, 0x0}, 0x0, 0x0, ...)
        /home/khoujani/go/pkg/mod/github.com/gocolly/colly@v1.2.0/colly.go:535 +0x645
github.com/gocolly/colly.(*Collector).Visit(0xc0002729c0?, {0xc0000c4b00?, 0x4?})
        /home/khoujani/go/pkg/mod/github.com/gocolly/colly@v1.2.0/colly.go:412 +0xa6
main.main()
        /home/khoujani/Desktop/eSport98/backend/eSport98-back/app/main2.go:192 +0x285

Process finished with the exit code 2

**Comment by WGH-** [comment]
Yeah, this is unfortunately expected that Instagram changes over time, and examples become outdated and no longer work.
